# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "VersionCheckExample" do
	pod 'RMAppStoreVersionCheck', :git => 'https://github.com/rocketmade/RMAppStoreVersionCheck.git', :branch => 'master', :commit => 'head'
end

