# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "VersionCheckExample" do
	pod 'RMAppStoreVersionCheck', :git => 'https://github.com/rocketmade/RMAppStoreVersionCheck.git', :tag => '1.0.0'
end

